export const products =
    [{ "name": "Beef - Sushi Flat Iron Steak", "precio": "€8,45", "stock": 14 },
    { "name": "Jolt Cola - Red Eye", "precio": "€8,57", "stock": 24 },
    { "name": "Soup V8 Roasted Red Pepper", "precio": "€6,54", "stock": 45 },
    { "name": "Egg - Salad Premix", "precio": "€9,24", "stock": 58 },
    { "name": "Eel Fresh", "precio": "€8,59", "stock": 93 },
    { "name": "Hummus - Spread", "precio": "€2,25", "stock": 0 },
    { "name": "Spinach - Baby", "precio": "€0,42", "stock": 35 },
    { "name": "Flour - Masa De Harina Mexican", "precio": "€6,10", "stock": 19 },
    { "name": "Cassis", "precio": "€0,15", "stock": 95 },
    { "name": "Eggplant - Asian", "precio": "€0,36", "stock": 46 },
    { "name": "Ocean Spray - Ruby Red", "precio": "€4,53", "stock": 1 },
    { "name": "Radish", "precio": "€6,91", "stock": 36 },
    { "name": "Pie Shells 10", "precio": "€3,65", "stock": 0 },
    { "name": "Muffin - Mix - Strawberry Rhubarb", "precio": "€6,13", "stock": 11 },
    { "name": "Vinegar - Cider", "precio": "€9,68", "stock": 42 },
    { "name": "Olives - Nicoise", "precio": "€9,85", "stock": 87 },
    { "name": "Veal - Brisket, Provimi, Bone - In", "precio": "€6,12", "stock": 17 },
    { "name": "Island Oasis - Banana Daiquiri", "precio": "€5,87", "stock": 44 },
    { "name": "Bread - Kimel Stick Poly", "precio": "€8,94", "stock": 56 },
    { "name": "Icecream Cone - Areo Chocolate", "precio": "€9,34", "stock": 64 }]