export const products =
    [{ "nombre": "Pepper - Paprika, Hungarian", "precio": "€2,25", "stock": 10 },
    { "nombre": "Bread - Sour Batard", "precio": "€8,65", "stock": 30 },
    { "nombre": "Gatorade - Cool Blue Raspberry", "precio": "€2,47", "stock": 62 },
    { "nombre": "Chips Potato Swt Chilli Sour", "precio": "€1,22", "stock": 2 },
    { "nombre": "Beef - Tenderloin Tails", "precio": "€5,54", "stock": 39 },
    { "nombre": "Straws - Cocktale", "precio": "€0,94", "stock": 19 },
    { "nombre": "Cheese Cloth No 100", "precio": "€0,24", "stock": 95 },
    { "nombre": "Curry Paste - Madras", "precio": "€9,02", "stock": 82 },
    { "nombre": "Wine - Magnotta - Pinot Gris Sr", "precio": "€1,03", "stock": 14 },
    { "nombre": "Mushroom - Chanterelle, Dry", "precio": "€2,85", "stock": 90 },
    { "nombre": "Sauce - Caesar Dressing", "precio": "€6,14", "stock": 6 },
    { "nombre": "Gin - Gilbeys London, Dry", "precio": "€6,26", "stock": 32 },
    { "nombre": "Toamtoes 6x7 Select", "precio": "€2,30", "stock": 21 },
    { "nombre": "Wine - Jaboulet Cotes Du Rhone", "precio": "€9,17", "stock": 56 },
    { "nombre": "Onions - Green", "precio": "€0,85", "stock": 11 },
    { "nombre": "Muffin Batt - Ban Dream Zero", "precio": "€6,96", "stock": 29 },
    { "nombre": "Nantucket - Pomegranate Pear", "precio": "€4,81", "stock": 86 },
    { "nombre": "Silicone Parch. 16.3x24.3", "precio": "€1,21", "stock": 26 },
    { "nombre": "Bread - Wheat Baguette", "precio": "€1,73", "stock": 33 },
    { "nombre": "Clams - Bay", "precio": "€9,29", "stock": 68 },
    { "nombre": "Snapple Lemon Tea", "precio": "€8,76", "stock": 60 },
    { "nombre": "Corn Shoots", "precio": "€7,76", "stock": 65 },
    { "nombre": "Soap - Pine Sol Floor Cleaner", "precio": "€4,27", "stock": 81 },
    { "nombre": "Apricots - Dried", "precio": "€3,91", "stock": 8 },
    { "nombre": "Celery", "precio": "€9,33", "stock": 62 },
    { "nombre": "Milk - 2% 250 Ml", "precio": "€1,96", "stock": 51 },
    { "nombre": "Veal - Heart", "precio": "€9,15", "stock": 11 },
    { "nombre": "Lettuce - Belgian Endive", "precio": "€7,76", "stock": 80 },
    { "nombre": "Tart Shells - Sweet, 3", "precio": "€2,64", "stock": 94 },
    { "nombre": "Bar Energy Chocchip", "precio": "€1,29", "stock": 9 },
    { "nombre": "Bread - Pullman, Sliced", "precio": "€0,97", "stock": 49 },
    { "nombre": "Lamb - Bones", "precio": "€0,86", "stock": 85 },
    { "nombre": "Plastic Arrow Stir Stick", "precio": "€9,35", "stock": 51 },
    { "nombre": "Mustard - Individual Pkg", "precio": "€8,14", "stock": 100 },
    { "nombre": "Beans - Yellow", "precio": "€2,11", "stock": 73 },
    { "nombre": "Energy Drink", "precio": "€6,52", "stock": 4 },
    { "nombre": "Basil - Primerba, Paste", "precio": "€4,99", "stock": 33 },
    { "nombre": "Pastry - Banana Muffin - Mini", "precio": "€5,36", "stock": 92 },
    { "nombre": "Tortillas - Flour, 12", "precio": "€4,87", "stock": 70 },
    { "nombre": "Oven Mitt - 13 Inch", "precio": "€0,40", "stock": 72 },
    { "nombre": "Flour - Rye", "precio": "€9,82", "stock": 67 },
    { "nombre": "Salami - Genova", "precio": "€8,24", "stock": 11 },
    { "nombre": "Chocolate - Pistoles, Lactee, Milk", "precio": "€8,10", "stock": 92 },
    { "nombre": "Wine - Port Late Bottled Vintage", "precio": "€3,21", "stock": 35 },
    { "nombre": "Vegetable - Base", "precio": "€7,92", "stock": 5 },
    { "nombre": "Spice - Onion Powder Granulated", "precio": "€3,80", "stock": 76 },
    { "nombre": "Duck - Fat", "precio": "€4,27", "stock": 17 },
    { "nombre": "Cheese - St. Paulin", "precio": "€7,77", "stock": 33 },
    { "nombre": "Banana", "precio": "€4,37", "stock": 1 },
    { "nombre": "Pear - Halves", "precio": "€3,68", "stock": 98 }]